### ISSUE TITLE
Add authentication to the registration process - 5.5 hours

### ISSUE THREAD

**Issue by amrioss** [gschool-blue-ocean/career-services-hub-20#60]

**Comment by jrm0527** [comment]
- Added check on students api to verify authentication code
- Added tscm to student based on verification code
- Added function to generate random code when creating a service manager
- Refactored faker to generate an email address using first.last@galvanize.com
- Adjusted tests to accommodate verification codes.
- Added authorization code display to manager career hub

**Comment by jrm0527** [comment]
Merged into dev
